apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: vertxdemo
  name: vertxdemo
  namespace: javademo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vertxdemo  
  template:
    metadata:
      labels:
        app: vertxdemo
    spec:    
      containers:
        - name: vertxdemo        
          image: burr/vertxdemo:v1
          resources:
            requests:
              memory: "300Mi"
              cpu: "250m"
            limits:
              memory: "400Mi"
              cpu: "1000m"          
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 3
          ports:
          - containerPort: 8080
      